# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, and test
        working-directory: ./source
        run: |
          npm install
          npm test 
        env:
          CI: true

  lint:
      runs-on: ubuntu-latest
          
      steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./source
        run: npm install
      - name: Run ESLint
        working-directory: ./source
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --ignore-pattern "jsdocs/**"
    
